### ISSUE TITLE
[FEAT] Release cycle management

### ISSUE THREAD

**Issue by b4nst** [loft-orbital/cuebe#27]
**Is your feature request related to a problem? Please describe.**

As for now `cuebe` is only able to create or patch resources. It cannot detect a resource deletion in the release. In order to fully  manage release lifecycle, we need a way to detect every drifts.  

**Describe the solution you'd like**

This solution should only rely on tools already present. So Go SDK and a Kubernetes cluster.
We should also avoid messing with the cluster state. The less object we have to create, the better.

**Additional context**

This is an open discussion before actually implementing a solution.

**Comment by astraios** [comment]
This very much looks like state management with a present/absent system. We could integrate a checksum component to detect changes in a resources. Could we keep that state in a "configmap"? per release maybe?

**Comment by b4nst** [comment]
Yup I was also thinking of something akin to a ConfigMap with one entry by resource managed in the release. For that we also need a way to uniquely identify a "release". A release UID.
A simple solution would be to add an argument to `apply` command, akin what's doing Helm with the `name` arg for `install` or `upgrade` commands.
Something smarter would not imply any input from user, as it is quite error prone and less convenient. I'm still trying to think of a smart way of extracting an UID from a release.

**Comment by b4nst** [comment]
So here is my proposal in order to keep `cuebe` agnostic of any way of deploying resources.

I propose to rely on a new label, `cuebe.loft-orbital.com/instance`. Like `app.kubernetes.io/instance` [is described](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels) as _A unique name identifying the instance of an application_ and `app.kubernetes.io/part-of` being _The name of a higher level application this one is part of_, `cuebe.loft-orbital.com/instance` would be _A unique name identifying the instance of a higher level application (release) this one is part of_.
As proposed by @astraios , a list of resources (namespace, kind and metadata.name) will be written in a config map named with the value of `cuebe.loft-orbital.com/instance`, in a special `cuebe-system` namespace. This will allow cross-namespace release management. 

I'll introduce 2 new cli flags to `cuebe`:
- `-i or --instance [instance-name]` will override or set `cuebe.loft-orbital.com/instance` to `instance-name` for every resources of the instance. This is a convenience flag if you don't want to hard code nor inject the value in your files. 
- `-p or --prune` when set, `cuebe` will remove every resources present in the config map that are not anymore in the actual instance (the one you're deploying)

Any resource without a `cuebe.loft-orbital.com/instance` label will be treated as _orphan_, meaning it will not be pruned in any way. `cuebe` could then provide command to attach / detach resources to / from an instance.

**Comment by astraios** [comment]
First, should the `-p | --prune` behaviour be the "default" behaviour and thus not requiring any args to be set? then we introduce something to "keep" the drift is a drift is detected? Cause I foresee I'll always be invoking the command with `-p` because I'll want all inconsistencies to be cleared up at each deploy.

Another idea, could be to honour a flag like KCC, e.g: `cnrm.cloud.google.com/deletion-policy: abandon`. TBH I have no strong opinion on this.

Then about the special namespace, I guess for now, it can be OK, it's just it will force "operators" to have permissions to CRUD objects in that additional namespace.

**Comment by b4nst** [comment]
The `deletion-policy` is actually a pretty good idea. It avoid the usage of yet another flag. We could add some dedicated command to cuebe to abandon a whole or part of an instance, just to simplify the work of writing labels.
